ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  resources :genres
  resources :platters

  root to: 'works#index'
  get '/works/(:id)' => 'works#select_images'

  resources :images
  resources :themes
  resources :values

  get 'main/index'

  get 'main/help'

  get 'main/about'

  get 'main/contacts'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/theme.rb
class Theme < ApplicationRecord
  has_many :images

  validates :name, presence: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :qty_items)
    end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/themes_helper.rb
module ThemesHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/themes/_form.html.slim
= form_for @theme, html: { class: "form-horizontal" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'text_field form-control'
  .form-group
    = f.label :qty_items, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :qty_items, class: 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), themes_path, class: 'btn btn-default'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/themes/edit.html.slim
- model_class = Theme
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/themes/index.html.slim
- model_class = Theme
.page-header
  h1=t '.title', default: model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:qty_items)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', default: t("helpers.actions")
  tbody
    - @themes.each do |theme|
      tr
        td= theme.id
        td= theme.name
        td= theme.qty_items
        td=l theme.created_at, format: :long
        td
          = link_to theme_path(theme), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_theme_path(theme), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to theme_path(theme), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
            = glyph 'remove'

= link_to t('.new', default: t("helpers.links.new")), new_theme_path, class: 'btn btn-primary'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/themes/new.html.slim
- model_class = Theme
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/themes/show.html.slim
- model_class = Theme
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @theme.name
      dt.label.label-default= model_class.human_attribute_name(:qty_items)
      dd
        pre.prettyprint= @theme.qty_items

.form-group
  = link_to t('.back', default: t("helpers.links.back")), themes_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_theme_path(@theme), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), theme_path(@theme), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'