ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  resources :genres
  resources :platters

  root to: 'works#index'
  get '/works/(:id)' => 'works#select_images'

  resources :images
  resources :themes
  resources :values

  get 'main/index'

  get 'main/help'

  get 'main/about'

  get 'main/contacts'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/platter.rb
class Platter < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  belongs_to :image

  validates_associated :genre, :image
  validates :name, :singer, :year, :genre_id, :user_id, presence: true
  validates :year, :genre_id, :image_id,  :user_id, numericality: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/platters_controller.rb
class PlattersController < ApplicationController
  before_action :set_platter, only: [:show, :edit, :update, :destroy]

  # GET /platters
  # GET /platters.json
  def index
    @platters = Platter.all
  end

  # GET /platters/1
  # GET /platters/1.json
  def show
  end

  # GET /platters/new
  def new
    @platter = Platter.new
  end

  # GET /platters/1/edit
  def edit
  end

  # POST /platters
  # POST /platters.json
  def create
    @platter = Platter.new(platter_params)

    respond_to do |format|
      if @platter.save
        format.html { redirect_to @platter, notice: 'Platter was successfully created.' }
        format.json { render :show, status: :created, location: @platter }
      else
        format.html { render :new }
        format.json { render json: @platter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platters/1
  # PATCH/PUT /platters/1.json
  def update
    respond_to do |format|
      if @platter.update(platter_params)
        format.html { redirect_to @platter, notice: 'Platter was successfully updated.' }
        format.json { render :show, status: :ok, location: @platter }
      else
        format.html { render :edit }
        format.json { render json: @platter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platters/1
  # DELETE /platters/1.json
  def destroy
    @platter.destroy
    respond_to do |format|
      format.html { redirect_to platters_url, notice: 'Platter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platter
      @platter = Platter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def platter_params
      params.require(:platter).permit(:name, :singer, :year, :genre_id, :image_id, :user_id, :description)
    end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/platters_helper.rb
module PlattersHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/platters/_form.html.slim
= form_for @platter, html: { class: "form-horizontal" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'text_field form-control'
  .form-group
    = f.label :singer, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :singer, class: 'text_field form-control'
  .form-group
    = f.label :year, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :year, class: 'text_field form-control'
  .form-group
    = f.label :genre_id, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :genre_id, class: 'text_field form-control'
  .form-group
    = f.label :image_id, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :image_id, class: 'text_field form-control'
  .form-group
    = f.label :user_id, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :user_id, class: 'text_field form-control'
  .form-group
    = f.label :description, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :description, class: 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), platters_path, class: 'btn btn-default'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/platters/edit.html.slim
- model_class = Platter
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/platters/index.html.slim
- model_class = Platter
.page-header
  h1=t '.title', default: model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:singer)
      th= model_class.human_attribute_name(:year)
      th= model_class.human_attribute_name(:genre_id)
      th= model_class.human_attribute_name(:image_id)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', default: t("helpers.actions")
  tbody
    - @platters.each do |platter|
      tr
        td= platter.id
        td= platter.name
        td= platter.singer
        td= platter.year
        td= platter.genre_id
        td= platter.image_id
        td= platter.user_id
        td= platter.description
        td=l platter.created_at, format: :long
        td
          = link_to platter_path(platter), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_platter_path(platter), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to platter_path(platter), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
            = glyph 'remove'

= link_to t('.new', default: t("helpers.links.new")), new_platter_path, class: 'btn btn-primary'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/platters/new.html.slim
- model_class = Platter
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/platters/show.html.slim
- model_class = Platter
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @platter.name
      dt.label.label-default= model_class.human_attribute_name(:singer)
      dd
        pre.prettyprint= @platter.singer
      dt.label.label-default= model_class.human_attribute_name(:year)
      dd
        pre.prettyprint= @platter.year
      dt.label.label-default= model_class.human_attribute_name(:genre_id)
      dd
        pre.prettyprint= @platter.genre_id
      dt.label.label-default= model_class.human_attribute_name(:image_id)
      dd
        pre.prettyprint= @platter.image_id
      dt.label.label-default= model_class.human_attribute_name(:user_id)
      dd
        pre.prettyprint= @platter.user_id
      dt.label.label-default= model_class.human_attribute_name(:description)
      dd
        pre.prettyprint= @platter.description

.form-group
  = link_to t('.back', default: t("helpers.links.back")), platters_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_platter_path(@platter), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), platter_path(@platter), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'