ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  resources :genres
  resources :platters

  root to: 'works#index'
  get '/works/(:id)' => 'works#select_images'

  resources :images
  resources :themes
  resources :values

  get 'main/index'

  get 'main/help'

  get 'main/about'

  get 'main/contacts'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :platters

  validates :name, presence: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/genres_helper.rb
module GenresHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/genres/_form.html.slim
= form_for @genre, html: { class: "form-horizontal" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = link_to t('.cancel', default: t("helpers.links.cancel")), genres_path, class: 'btn btn-default'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/genres/edit.html.slim
- model_class = Genre
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/genres/index.html.slim
- model_class = Genre
.page-header
  h1=t '.title', default: model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', default: t("helpers.actions")
  tbody
    - @genres.each do |genre|
      tr
        td= genre.id
        td= genre.name
        td=l genre.created_at, format: :long
        td
          = link_to genre_path(genre), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do
            = glyph 'info-sign'
          = link_to edit_genre_path(genre), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do
            = glyph 'pencil'
          = link_to genre_path(genre), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do
            = glyph 'remove'

= link_to t('.new', default: t("helpers.links.new")), new_genre_path, class: 'btn btn-primary'

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/genres/new.html.slim
- model_class = Genre
.page-header
  h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/genres/show.html.slim
- model_class = Genre
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

.fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @genre.name

.form-group
  = link_to t('.back', default: t("helpers.links.back")), genres_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_genre_path(@genre), class: 'btn btn-default'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), genre_path(@genre), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'