ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  resources :genres
  resources :platters

  root to: 'works#index'
  get '/works/(:id)' => 'works#select_images'

  resources :images
  resources :themes
  resources :values

  get 'main/index'

  get 'main/help'

  get 'main/about'

  get 'main/contacts'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :platters

  validates :name, presence: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/image.rb
class Image < ApplicationRecord
  belongs_to :theme
  has_many :values
  has_one :platter

  validates_associated :theme, :values
  validates :name, :file, :theme_id, presence: true
  validates :theme_id, numericality: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/platter.rb
class Platter < ApplicationRecord
  belongs_to :genre
  belongs_to :user
  belongs_to :image

  validates_associated :genre, :image
  validates :name, :singer, :year, :genre_id, :user_id, presence: true
  validates :year, :genre_id, :image_id,  :user_id, numericality: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/theme.rb
class Theme < ApplicationRecord
  has_many :images

  validates :name, presence: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/user.rb
class User < ApplicationRecord
  has_many :values
  has_many :platters

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
  validates_associated :values, :platters
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/models/value.rb
class Value < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates :value, :user_id, :image_id, presence: true
  validates :user_id, :image_id, :value, numericality: true
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def help
  end

  def about
  end

  def contacts
  end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @themes = Theme.all
  end

  def select_images
    @images = Theme.find(params[:id]).images.pluck(:file)
    respond_to do |format|
      format.json { render json: @images }
    end
  end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/application_helper.rb
module ApplicationHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/genres_helper.rb
module GenresHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/images_helper.rb
module ImagesHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/main_helper.rb
module MainHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/platters_helper.rb
module PlattersHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/sessions_helper.rb
module SessionsHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/themes_helper.rb
module ThemesHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/values_helper.rb
module ValuesHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/helpers/works_helper.rb
module WorksHelper
end

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title Experteese
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      .row
        .col-sm-10.col-sm-offset-1
          = render "shared/header"
          - flash.each do |key, value|
            div class=("alert alert-#{key}") = value
          = yield
          .navbar-fixed-bottom.row-fluid
            = render "shared/footer"
          = debug(params) if Rails.env.development?

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains #{pluralize(@user.errors.count, "error")}.
    ul
      - @user.errors.full_messages.each do |msg|
        li
          | * #{msg}

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/shared/_footer.html.slim
p.text-center
  | Copyright © 2016 Tatyana Ezhova

ezhovaproject-8802f9ee6258a883790ccf4d9397b7eb1ab1392d/app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      a.navbar-brand href="/main/index"
        b Experteese
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li = link_to 'Главная', main_index_path
        li = link_to 'Контакты', main_contacts_path
        li = link_to 'О нас', main_about_path
        li = link_to 'Помощь', main_help_path
        li = link_to 'Пользователи', users_path
        li = link_to 'Войти', signin_path